### ISSUE TITLE
Parent-child composition

### ISSUE THREAD

**Issue by iyegoroff** [ncthbrt/react-use-elmish#4]
How to implement communication between components like in Elmish? There is no analog to Cmd.map - should I use custom effect creator or there is another approach?

**Comment by ncthbrt** [comment]
It depends on whether you want to map your dispatch function or not.

If you declare a union: `type Action = SubtypeA | SubtypeB` in typescript,
and your dispatcher is `Dispatch<Action>`, the dispatcher is also
`Dispatch<SubtypeA>` due to the nature of the type system. So you could
have a component declare that it only cares about a subset of actions and
have it take in the raw dispatch without mapping.

Alternatively if you want to map your state or dispatch, you could use the
useMemo and useCallback hooks to map state and dispatch respectively.

**Comment by iyegoroff** [comment]
Thanks for the explanation!
